apiVersion: apps/v1
kind: Deployment
metadata:
  name: sampleapi-deployment
  labels:
    app: sampleapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sampleapi
  template:
    metadata:
      labels:
        app: sampleapi
      annotations: 
        prometheus.io/scrape: "true"
        prometheus.io/port: "80"
        prometheus.io/path: "/metrics" 
    spec:
      containers:
        - name: sampleapi
          image: public.ecr.aws/p3q4d0z4/sampleapi:{{TAG}}
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: DB_SAMPLE_MSQL
              value: server=sample-db-hml.cdz1u8qrhkma.us-east-1.rds.amazonaws.com;database=sample_db;user=admin;password=Vini#0102Mi
            - name: APPLICATION_NAME
              value: sampleapi
---

apiVersion: v1
kind: Service
metadata:
  name: sampleapi-service
spec:
  type: LoadBalancer
  selector:
    app: sampleapi
  ports:
    - protocol: TCP
      port: 80
 

---